version: '3.3'

services:
  app:
    container_name: "api-starwars"
    build: .
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - "db"
    command: "yarn dev"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: starwars

