
GET  http://localhost:3000/api/v1/graphql
Content-Type: application/json
x-api-key: bc790454-5207-4e64-96af-461ef58dbb9e
Authorization: Bearer bc790454-5207-4e64-96af-461ef58dbb9e
X-REQUEST-TYPE: GraphQL

query {
  allPlanets{
    id
    name
  }
}
###

GET http://localhost:3000/api/v1/graphql
Content-Type: application/json
x-api-key: bc790454-5207-4e64-96af-461ef58dbb9e
Authorization: Bearer bc790454-5207-4e64-96af-461ef58dbb9e
X-REQUEST-TYPE: GraphQL

query {
  onePlanets(id: "0ea6d8ff-2e39-44ca-bd52-ed12b4b349b7"){
    id
    name
  }
}
