
GET  http://localhost:3000/api/v1/graphql
Content-Type: application/json
x-api-key: 1f31f58a-e3bc-4d55-82ad-eeed777ab6ee
Authorization: Bearer 1f31f58a-e3bc-4d55-82ad-eeed777ab6ee
X-REQUEST-TYPE: GraphQL

query {
  allPlanets{
    id
    name
  }
}
###

GET http://localhost:3000/api/v1/graphql
Content-Type: application/json
x-api-key: 1f31f58a-e3bc-4d55-82ad-eeed777ab6ee
Authorization: Bearer 1f31f58a-e3bc-4d55-82ad-eeed777ab6ee
X-REQUEST-TYPE: GraphQL

query {
  onePlanet(id: "cdc9cef1-8930-4aee-938f-8610eb918e2c"){
    id
    name
  }
}
